server:
  port: 18080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.100.82.183:3306/work?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #    ip
    host: 192.168.31.50
    #    端口
    port: 6379
    #    密码，默认空
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000

  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.31.50
    port: 5672
    username: gaopengtao
    password: gaopengtao

mybatis:
  mapper-locations: classpath:com/example/mywork/mapper/*.xml

logging:
  # 设置logback.xml位置
  #  config: classpath:log/logback.xml
  # 设置log4j.properties位置
  config: classpath:log4j.properties

